from .blue import (
    IsolateHost,
    RestoreHost,
    Monitor,
    Analyze,
    DeployDecoy,
    Remove,
    RestoreFromBackup,
    DecoyApache,
    DecoySSHD,
    DecoyTomcat,
    Misinform,
    ConfigureACL,
)
from .red import (
    NetworkScan,
    DiscoverRemoteSystems,
    DiscoverNetworkServices,
    ExploitRemoteService,
    PrivilegeEscalate,
    Impact,
    ExploitBlueKeep,
    ExploitEternalBlue,
    ExploitHTTP_RFI,
    JuicyPotato,
    V4L2KernelExploit,
    KillProcess,
    ShareIntelligence,
    OverloadPLC,
)

__all__ = [
    'IsolateHost',
    'RestoreHost',
    'Monitor',
    'Analyze',
    'DeployDecoy',
    'Remove',
    'RestoreFromBackup',
    'DecoyApache',
    'DecoySSHD',
    'DecoyTomcat',
    'Misinform',
    'ConfigureACL',
    'NetworkScan',
    'DiscoverRemoteSystems',
    'DiscoverNetworkServices',
    'ExploitRemoteService',
    'PrivilegeEscalate',
    'Impact',
    'ExploitBlueKeep',
    'ExploitEternalBlue',
    'ExploitHTTP_RFI',
    'JuicyPotato',
    'V4L2KernelExploit',
    'KillProcess',
    'ShareIntelligence',
    'OverloadPLC',
    'SecurityAwarenessTraining',
    'DeployHoneytoken',
]

from .blue import SecurityAwarenessTraining
from .blue import DeployHoneytoken

__all__.extend(['SecurityAwarenessTraining', 'DeployHoneytoken'])
