import random
from typing import Any, Dict


class GreenAgent:
    """Simulates benign corporate users to generate behavioral background noise
    and false-positive alerts, masking Red Agent activity.

    It operates on a Day/Night cycle across the simulated business hours.
    """

    def __init__(self, agent_id: str = 'green_agent_0'):
        self.agent_id = agent_id
        from netforge_rl.siem.event_templates import evid_4624, sysmon_3, evid_4688

        self._benign_templates = [evid_4624, sysmon_3, evid_4688]

    def generate_noise(self, current_tick: int, global_state: Any) -> Dict[str, Any]:
        """Generates random telemetry alerts based on the current tick's position
        within the day/night cycle.

        Args:
            current_tick (int): The current chronological tick of the environment.
            global_state (GlobalNetworkState): The architecture state to extract subnets/hosts.

        Returns:
            Dict[str, Any]: A dictionary representing telemetry generated by this tick.
        """
        # Day: Ticks 0 to 100, Night: Ticks 101 to 149
        cycle_position = current_tick % 150
        is_day = cycle_position <= 100

        noise_logs = []
        hosts = list(global_state.all_hosts.values())
        if not hosts:
            return {'alerts': []}

        # Higher activity and more false positives during the day
        probability_of_noise = 0.8 if is_day else 0.1
        probability_of_false_positive = 0.05 if is_day else 0.01

        if random.random() < probability_of_noise:
            # Generate benign background traffic
            source = random.choice(hosts)
            target = random.choice(hosts)
            if source.ip != target.ip:
                template = random.choice(self._benign_templates)
                log_string = template(source.ip, target.ip)
                noise_logs.append(
                    {
                        'type': 'benign_xml',
                        'data': log_string,
                        'subnet': source.subnet_cidr,
                    }
                )

        if random.random() < probability_of_false_positive:
            # Generate a false positive anomaly that could trip Blue's SIEM
            target = random.choice(hosts)
            from netforge_rl.siem.event_templates import evid_4625

            log_string = evid_4625(
                'unknown_external', target.ip, username='Administrator'
            )
            noise_logs.append(
                {
                    'type': 'anomaly_xml',
                    'data': log_string,
                    'subnet': target.subnet_cidr,
                }
            )

        return {'alerts': noise_logs}
